### ISSUE TITLE
Error in a2plib.py:988 "name 'a' is not defined"

### ISSUE THREAD

**Issue by Andy1978** [kbwbe/A2plus#410]
A2plus V0.4.48 (FreeCAD info at bottom)

[A2plus_problem_pin_hole.zip](https://github.com/kbwbe/A2plus/files/5864591/A2plus_problem_pin_hole.zip)

Open FreeCAD, Create New, switch to A2Plus workbench, save as "assembly.FCStd".
Add hole.FXStd first, then pin.FCStd.
Select circle on hole, STRG + select circle on pin (see screenshot1.png)
![a2plus_screenshot1](https://user-images.githubusercontent.com/240064/105668787-54991000-5ede-11eb-9596-16505a576a19.png)

Click "Add an axisCoincidence constraint"

An error is shown in the console:
------------------------------------------------------------------------
Running the Python command 'a2p_AxialConstraintCommand' failed:
Traceback (most recent call last):
  File "/home/andy/.FreeCAD/Mod/A2plus/a2p_constraintcommands.py", line 167, in Activated
    c = a2p_constraints.AxialConstraint(selection)
  File "/home/andy/.FreeCAD/Mod/A2plus/a2p_constraints.py", line 386, in __init__
    self.create(selection)
  File "/home/andy/.FreeCAD/Mod/A2plus/a2p_constraints.py", line 104, in create
    self.calcInitialValues() #override in subclass !
  File "/home/andy/.FreeCAD/Mod/A2plus/a2p_constraints.py", line 391, in calcInitialValues
    axis2 = getAxis(self.ob2, c.SubElement2)
  File "/home/andy/.FreeCAD/Mod/A2plus/a2plib.py", line 988, in getAxis
    axis = a.Axis

name 'a' is not defined
------------------------------------------------------------------------

The pin is originally part of bigger STEP created by "PDElib Version 3.2.7"
and I'm unsure if I'm allowed to upload the whole STEP file due to copyright restrictions.

It looks for me like the code at a2plib.py:988 is trying to find the axis for an edge made out of multiple arcs but fails. Its clear for me that there is something special for this part but since the code already tries to address this corner case I would consider this as bug. 

OS: Debian GNU/Linux 10 (buster) (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23578 (Git) AppImage
Build type: Release
Branch: master
Hash: 50c3cbf00579dc4941ca743c25720d016b0453ce
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: German/Germany (de_DE)

**Comment by Andy1978** [comment]
Oh my bad, already fixed in V0.4.49, closing issue
Thanks for your fast response
