### ISSUE TITLE
Preference page is corrupt

### ISSUE THREAD

**Issue by hasecilu** [kbwbe/A2plus#635]
Opening FreeCAD preferences page after loading the WB crashes FreeCAD.

0.22.0dev AppImage on Arch Linux, crashes on X.org Openbox and Wayland Hyprland

At least with the 36807 old compilation I'm able to open the preferences page with no crash.

I opened a lot of other external WB but there is no crash with them, it's odd.

Got this error on Openbox
```python
Initializing A2plus Workbench v0.4.66.

"Empty widget item in QVBoxLayout 'verticalLayout_10'."
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3d1d0) [0x72c0dca4c1d0]
#1  0x72c0ddd8f7bc in QLayout::setContentsMargins(int, int, int, int) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Widgets.so.5+0xc
#2  0x72c0dfceb24c in Gui::Dialog::DlgPreferencesImp::createPreferencePage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0xbc
#3  0x72c0dfcedd17 in Gui::Dialog::DlgPreferencesImp::createPageInGroup(Gui::Dialog::PreferencesPageItem*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x107
#4  0x72c0dfcef350 in Gui::Dialog::DlgPreferencesImp::setupPages() from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x60
#5  0x72c0dfcef424 in Gui::Dialog::DlgPreferencesImp::DlgPreferencesImp(QWidget*, QFlags<Qt::WindowType>) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0xa4
#6  0x72c0dfbbdb9e in StdCmdDlgPreferences::activated(int) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x3e
#7  0x72c0dfb93c08 in Gui::Command::_invoke(int, bool) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x2a8
#8  0x72c0dfb93fc4 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x134
#9  /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5(+0x2eb6f2) [0x72c0dceeb6f2]
#10  0x72c0ddd6a462 in QAction::triggered(bool) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Widgets.so.5+0x32
#11  0x72c0ddd6ce2b in QAction::activate(QAction::ActionEvent) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Widgets.so.5+0xab
#12  0x72c0dfbf1ff0 in Gui::ShortcutManager::onTimer() from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x100
#13  0x72c0dfbf2ffd in Gui::ShortcutManager::checkShortcut(QObject*, QKeySequence const&) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x52d
#14  0x72c0dfbf5267 in Gui::ShortcutManager::eventFilter(QObject*, QEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x97
#15  0x72c0dceb67ca in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5+0x6a
#16  0x72c0ddd703e8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Widgets.so.5+0xb8
#17  0x72c0dfb3e3b9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x99
#18  0x72c0dceb6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5+0x108
#19  0x72c0dd562d63 in QShortcutMap::dispatchEvent(QKeyEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Gui.so.5+0x423
#20  0x72c0dd56368b in QShortcutMap::tryShortcut(QKeyEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Gui.so.5+0x5b
#21  0x72c0dd50e60a in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Gui.so.5+0x16a
#22  0x72c0dd53129f in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Gui.so.5+0x7f
#23  0x72c0dd50b0bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Gui.so.5+0xac
#24  /tmp/.mount_freecaTjuOco/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x64bea) [0x72c0d6e0bbea]
#25  /tmp/.mount_freecaTjuOco/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x72c0db9e6ad7]
#26  /tmp/.mount_freecaTjuOco/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x72c0db9e9ac7]
#27  /tmp/.mount_freecaTjuOco/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x72c0db9ea0ce]
#28  0x72c0dcf0aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5+0x66
#29  0x72c0dceb570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5+0x11b
#30  0x72c0dcebd212 in QCoreApplication::exec() from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libQt5Core.so.5+0x82
#31  0x72c0dfa9f883 in Gui::Application::runApplication() from /tmp/.mount_freecaTjuOco/usr/bin/../lib/libFreeCADGui.so+0x983
#32  /tmp/.mount_freecaTjuOco/usr/bin/freecad(+0x7620) [0x5852c72d7620]
#33  /usr/lib/libc.so.6(+0x25e08) [0x72c0dca34e08]
#34  /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x72c0dca34ecc]
#35  /tmp/.mount_freecaTjuOco/usr/bin/freecad(+0x7981) [0x5852c72d7981]
```

### About FreeCAD
```
OS: LainOS (XFCE/openbox)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git) AppImage
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Japanese/Japan (ja_JP)
Installed mods: 
  * Alternate_OpenSCAD.backup1724346061.0545766 1.0.0 (Disabled)
  * ThreadProfile 1.92.0
  * FreeCAD-Movie 2024.2.15
  * freecad.gears 1.2.0
  * PieMenu 1.8.0
  * freecad_metal_workbench 0.0.1
  * Ship 2022.4.11
  * OpenTheme 2024.8.17
  * FreeGrid 2.0.0
  * FreeCAD-Reinforcement
  * Defeaturing 1.2.2
  * FreeCAD_SheetMetal 0.4.16
  * FreeCAD-Pyramids-and-Polyhedrons
  * yaml-workspace 0.1.2
  * woodworking 0.21.2.33771
  * Assembly4 0.50.15
  * FastenersWB 0.5.27
  * lattice2 1.0.0
  * Rocket 3.3.0
  * dodo 1.0.1
  * DidYouKnowThat
  * FreeCAD-motion
  * cadquery_module
  * MnesarcoUtils 0.2.5 (Disabled)
  * Profiles 0.0.1
  * Alternate_OpenSCAD 1.0.0
  * osh-autodoc-workbench 0.2.3
  * CfdOF 1.27.5
  * A2plus 0.4.66
  * kicadStepUpMod 11.2.4
  * Nodes 0.1.36
  * Marz 0.1.8
  * frame 0.1.1
  * Curves 0.6.45
  * pcb 6.2023.1
  * FreeCAD_assembly3 0.12.2
  * Render 2024.8.4
```

**Comment by hasecilu** [comment]
I tried moving the elements changing layout and removing extra red boxes and seems to work now (yesterday wasn't)
![ss](https://github.com/user-attachments/assets/ee8bafd2-adca-4ba5-a03a-e93517e1f51d)

**Comment by Luciniki** [comment]
It seems to me the same as the problem (633) that I found on windows.
The source of the bug should be the same.

**Comment by hasecilu** [comment]
Didn´t noticed #633! Did you already tested the change from #638? That should fix the problem meanwhile.

**Comment by Luciniki** [comment]
Yes, everything went well!
Thank you
